### ISSUE TITLE
Summary Index BackgroudNoise outputs very large values

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/audio-analysis#187]
### Expected behaviour

Valid values for `BackgroundNoise` are always output.

### Actual behaviour

Sometimes very very large values are output, e.g. `1.79769313486232E+308`. This value is actually larger than `double.MaxValue` because CSV serialization truncates the double value and rounds it up. 😕 

This may not be a bug, but it would be good to check if outputting `double.MaxValue` was actually intended in this case.

### Steps to reproduce the behaviour

- What command did you use?
  - The standard indices generation command for ICD=60.0
- What config file did you use?
  - The standard indices config file
- Where can we find the source data used?
  - This data is private. Contact @atruskie for the path (`112/.../20180214_101121_Bar5.wav`)

### Any other details?

I've included the serialization part of this bug into https://github.com/QutEcoacoustics/audio-analysis/issues/181

**Comment by atruskie** [comment]
This is potentially fixed in https://github.com/QutEcoacoustics/audio-analysis/commit/61ec95242b8b130f8753d27d43ff356183262f86#diff-c1b3b62005ae2dcad37ce35db3de36d7L118

@towsey will cofirm tomorrow.

**Comment by towsey** [comment]
I believe I have fixed this issue caused by taking log of a zero value.
3 changed files
Commit e8f9a31
