### ISSUE TITLE
Include Feature on Config File Towsey.Acoustic

### ISSUE THREAD

**Issue by elizianeoliveira** [QutEcoacoustics/audio-analysis#192]
## Is your feature request related to a problem? Please describe.
Is not possible to change the configurations of the false colour spectrograms on audio2csv analysis, like indices used to produce the FC and axis interval.

## Describe the solution you'd like
Include the options presented in the SpectogramFalseColourConfig.yml in audio2csv analysis.

**Comment by atruskie** [comment]
Closed by #231 in 5630edde8e59e9694979a27d477df0e42bc54c73 and 934f466a3d61f7ad6780813eee20e7b2c83d0373
