### ISSUE TITLE
AP.Settings.config can't be loaded on case-sensitive filesystems

### ISSUE THREAD

**Issue by jakeanq** [QutEcoacoustics/audio-analysis#193]
## Describe the bug
On case-sensitive file systems, `AP.Settings.config` cannot be found as the program looks for `AP.Settings.Config` instead.  This causes `mono AnalysisPrograms.exe CheckEnvironment` to fail.

## Expected behavior 
Expected the config file to load normally and `mono AnalysisPrograms.exe CheckEnvironment` to succeed.

## Diagnostics

- [X] I Confirm I have followed [the instructions for reporting a bug](https://github.com/QutEcoacoustics/audio-analysis/blob/master/docs/bug_report.md)
- [X] I have attached a log
```
QUT Ecoacoustics Analysis Programs - version 18.6.3.3 (RELEASE build, 2018-06-25T11:44:54.4214477Z)
Git branch-version: master-1287737fd89a2ca68fefa51e1be579faf01bae21, DirtyBuild:False, CI:481
Copyright 2018 QUT
[2018-10-17T11:24:06.1127720+10:30] INFO  - Checking required executables can be found
Fatal error:
  Configuration exception: An exe path for `AudioUtilityWvunpackExeLinux` was not found in AP.Settings.config
```

- [x] I have answered the following questions

**Operating system:**
Arch Linux (Ext4 filesystem)

NB: Bug will occur on any case-sensitive filesystem regardless of operating system.

**AP.exe version:**
16.6.3.3

**The data used can be found:**
N/A

**The command I used:**
 `mono AnalysisPrograms.exe CheckInstall`

**The config file I used:**
The default `AP.Settings.config` file

### Screenshots
N/A

## Additional Details
[Patch file with suggested fix](https://github.com/QutEcoacoustics/audio-analysis/files/2485517/CaseSensitivity.zip)

**Comment by atruskie** [comment]
Thanks for the report @jakeanq. There are some larger config problems that need to be fixed but we should be able to get this fixed with them.
