### ISSUE TITLE
Generate all grayscale single-index spectrograms

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/audio-analysis#199]
## Is your feature request related to a problem? Please describe.
The spectral indices are rendered as grayscale spectrogram images for the six spectral indices used in the false colour spectrogram colour-maps. Here an example grayscale spectral ACI spectrogram:

![fi_location_sm304246_mcleodroad_20180912__aci](https://user-images.githubusercontent.com/1452968/47193599-26d7cf00-d397-11e8-8f5b-fa2e9bcc2283.png)

## Describe the solution you'd like

Two fold:
- By default generate the grayscale spectrograms for all spectral indices
- Add a new option to the `Towsey.Acoustic.yml` config to limit or disable index image generation
   - The config option will have a name like `GenerateIndicesImages` which will take a value of `All`, `CompositeOnly`, `SingularOnly`, `None`

## Describe alternatives you've considered

We have considered removing image generation all together from the `Towsey.Acoustic` analysis since most people want concatenated images produced fror multiple files - there's no use generating the images twice.

## Additional context
The single-index spectrograms are very useful for examining the effects of different indices without the colour bias or confounding effects that are found in the false colour spectrograms.

**Comment by towsey** [comment]
The request is to generate single index (grey scale) concatenated 24-hour spectrograms of all the indices for which matrices of values are available. This will assist the search for those indices that detect acoustic events of interest. And this, in turn, is useful when constructing feature sets for ML purposes.
I agree that there is no need to construct any of the "partial" spectrogram images" where the ultimate intention is to produce 24 hour spectrograms.

**Comment by atruskie** [comment]
@towsey the 24-hour clarification is not needed. The `concatenateIndexFiles` command (which produces 24-hour FCS) should have identical behaviour to the `Towsey. Acoustic` analysis. This modification as such is really a change to the data _contract_ of an indices analysis and thus both bits of command need new behaviour. 

Keep in mind we have no limitation on the length of a recording... Just the other day we were processing 24-hour files. 

As to to the 'partial' images: images associated with the recording are the whole image. Concatenated images are super images.

**Comment by towsey** [comment]
Reopened because these code written for this patch only generated the extra images in the concatenate path. More work required to do this for also the standard index generation path.
