### ISSUE TITLE
Incorrect rendering of File joins when Concatenating

### ISSUE THREAD

**Issue by towsey** [QutEcoacoustics/audio-analysis#210]
## Describe the bug
When concatenating summary indices, every second set of indices (i.e. from every second audio file) is overdrawn with a pink segment, which is labelled file join. For example of this bug, see <Y:\Results\20181016-143849 - Liz, Towsey.Indices, #231\ConcatResult\TimedGaps\Znidersic\FrenchIsland\201808\FI_Location_SM304253_GartsidesTrack\20180821.FI_Location_SM304253_GartsidesTrack_20180821__SummaryIndices.png>

## Expected behavior 
Only need a one pixel wide vertical pink line to indicate a file join.

## Diagnostics
This is due to a bug in AudioAnalysisTools.Indices.GapsAndJoins.DataIntegrityCheckForFileJoins().
It sets the end of each join to be the end of the file segment.
Instead the end of each join should be just one pixel/time index after its start.

- I Confirm I have followed [the instructions for reporting a bug](https://github.com/QutEcoacoustics/audio-analysis/blob/master/docs/bug_report.md)
- I have attached a log <N/A>
- I have answered the following questions:
  <N/A>  - **Operating system:** 
  <N/A>  - **AP.exe version:**
  
## Solution
The method GapsAndJoins.DataIntegrityCheckForFileJoins() can be changed so that endPosition is only one index greater than start position.

**Comment by atruskie** [comment]
Can you attach an image that shows the problem, please?

In the spectrum part of the image (the raster data), there should be no metadata rendered for adjacent blobs of data.

**Comment by towsey** [comment]
Here is example of the problem
![fi_location_sm304253_gartsidestrack_20180821__summaryindices](https://user-images.githubusercontent.com/7237507/51649136-e8256680-1fce-11e9-8096-6e2d38e8a1d1.png)

**Comment by atruskie** [comment]
Ah, I see.

Your proposed fix is good 👍

I'd suggest moving the _File join_ text more to the left so more of it is readable.

**Comment by towsey** [comment]
Hello again Anthony,
I am trying to commit my changes, but GitHub says changes have been made in the repository.
Below is git status.
How to proceed with this?

C:\Work\GitHub\audio-analysis>git status
On branch Issue154
Your branch and 'origin/Issue154' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean



Dr. Michael Towsey
ORCID iD http://orcid.org/0000-0002-8246-7151
QUT Ecoacoustics Research Group  |  www.Ecosounds.org<http://www.ecosounds.org/>
Science and Engineering Faculty
S block, Level 10, Room 1002, Garden Point Campus,
Queensland University of Technology,
Brisbane, Queensland 4001
Australia
Phone +61 7 3138 9381
Fax     +61 7 3138 9390
________________________________

**Comment by atruskie** [comment]
@towsey: switch  back to master before making new changes

**Comment by towsey** [comment]
I have created a new branch to deal with this issue. I believe I have fixed it but not tested it. Furthermore still having trouble with the ambiguous Run call in the new branch which I could not fix by casting. So I simply committed the branch and will let you fix things.

**Comment by atruskie** [comment]
It's because you put that fix in on the other branch in a commit that duplicated my fix https://github.com/QutEcoacoustics/audio-analysis/pull/209/commits/e51f72c52b4f162c44f574e11518cb129d72da72 😕

**Comment by atruskie** [comment]
Closed by 981696dd51d759a3d6c17fd88a53c498a5c9c5a7 and ce80cbcd019613db03446ba1189117ab42457afe
