### ISSUE TITLE
Change rendering of the Summary Indices tracks image

### ISSUE THREAD

**Issue by towsey** [QutEcoacoustics/audio-analysis#212]
## Is your feature request related to a problem?
It is difficult to follow the summary index tracks (in the summary index images) across 24hour scale to find out what name is on the right hand side.

## Describe the solution you'd like
The background for consecutive / alternate tracks can be in slightly different  shading as is done in many forms with multiple lines. 

Also change the end of track descriptor rendering so that it is easier to collow.

**Comment by atruskie** [comment]
This enhancement should not break any known uses of this image: sounds good 👍
