### ISSUE TITLE
Ecosounds.AED analysis on 1 hour file

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/audio-analysis#220]
## Describe the bug
Fatal crash when running Ecosounds.AED on a koala file, unsure why its crashing so I've left all the required documents needed to replicate the problem.

## Expected behavior 
audio2csv should run through the analysis without crashing, if it does not find what it is looking for the system should exit gracefully.

## Diagnostics
Windows 10 Home Version 1803
AP Version 18.6.3.3
Command: `AnalysisPrograms.exe audio2csv audioFile.wav C:\AP\ConfigFiles\Ecosounds.AED "C:/AP Desktop"`
[Log](https://github.com/QutEcoacoustics/audio-analysis/files/2934700/Terminal.Output.txt)
[Audio](https://drive.google.com/open?id=1MC3etu_zZSdLo8r_TsQOQICRndnIYD-t)
Please tell me when you have downloaded the audio so i can remove it from my drive.

**Comment by atruskie** [comment]
@Allcharles please actually submit the log file when filing a bug report rather than just the terminal output.

Instructions here: https://github.com/QutEcoacoustics/audio-analysis/blob/master/docs/bug_report.md

You may delete the files.
