### ISSUE TITLE
Flying Fox Recogniser

### ISSUE THREAD

**Issue by towsey** [QutEcoacoustics/audio-analysis#238]
##
I have proposed that the recogniser have following steps:
1. Break long recordings into one-minute segments.
2. Convert each segment to a spectrogram.
3. Obtain a noise profile for each segment. This is to be used later to remove insect chorusing.
4. Scan the one-minute waveform and select "spike maxima" whose amplitude exceeds a decibel threshold, D.
5. Extract a single frame (say 512 samples) centred on each spike and convert to a spike spectrum.
6. Subtract the noise profile from the spike spectrum.
7. Smooth the remaining spectrum.
8. Look for evenly spaced harmonics in the smoothed spectrum. Typically the lowest harmonic will lie between 1200 Hz and 3000 Hz and the higher ones evenly spaced. This is the tricky bit due to variability but may work to use auto-correlation.

**Comment by atruskie** [comment]
Hi @towsey,

Some notes from our meeting with Gary Plamer:

- labelled examples (labelled with Audacity) are here: `Y:\Gary Palmer\Flying Fox\Examples`
- 3 species, all not-distinguishable with acoustics
- they are interested in recognizing three types of acoustic events:
  - territorial calls: short, single-syllable, amplitude modulated, screeches with stacked harmonics
  - agonistic calls: longer calls, multiple-syllables, seem to a series of warbling harmonic syllables, approximately 5-7 seconds long
  - wingbeats: a series of impulses in rapid succession
- additionally, it would be good if we report the
  - dominant frequency (where applicable)
  - and the dominant frequency intensity
