### ISSUE TITLE
False Colour Spectrograms using AP.exe

### ISSUE THREAD

**Issue by tinchobulen** [QutEcoacoustics/audio-analysis#246]
Hello @atruskie 

I'm trying to complete de analysis by working on the next step: to create FC spectrograms using as input the .csv files generated by audio2csv command.

perhaps my new R script is wrong.

## Describe the bug

Unrecognized command or argument: 

'D:/AP/results_AP_laguna/Mixdown_laguna.wav/Towsey.Acoustic/Mixdown_laguna__Towsey.Acoustic.SUM.csv'

The output is a set of empty folders named as each index .csv file from the directory folder.

## Expected behavior 

To create FC spectrograms derived by several indices files generated in the previous step.

## Diagnostics

- I have attached a log 
[log_20190719T131019Z.txt](https://github.com/QutEcoacoustics/audio-analysis/files/3411204/log_20190719T131019Z.txt)

- I have answered the following questions:
    
  - **Operating system:**  Windows 10 Version 1809 18.05.3.6
  - **AP.exe version:** 19.5.1.1 (DEBUG build, 2019-05-12T14:00:59.1189820Z)
  - **The command I used:** 
```
###AP_analysis###
rm(list=ls())
##Scripting with R
# Set the directory containing the files

"D:/AP/results_AP_laguna/Mixdown_laguna.wav/Towsey.Acoustic" -> directory


# The directory to store the results

 "D:/AP/FC_spectrogram_laguna"-> base_output_directory 

# Get a list of audio files inside the directory
# (Get-ChildItem is just like ls, or dir)

files <- list.files(directory, pattern = ".csv", full.names = TRUE)

files

# iterate through each file
for(file in files) {
  message("Processing ", file) 
  
  # get just the name of the file
  file_name <- basename(file)
  
  # make a folder for results
  output_directory <- normalizePath(file.path(base_output_directory, file_name))
  dir.create(output_directory, recursive = TRUE)
  
  # prepare command
  command <- sprintf('DrawLongDurationSpectrograms "%s" SpectrogramFalseColourConfig.yml "%s" IndexPropertiesConfigForFrogs.yml', file, output_directory)
  
  # finally, execute the command
  system2("D:/AP/AnalysisPrograms.exe", command)
}
```

  - **The config file I used:**  SpectrogramFalseColourConfig.yml, IndexPropertiesConfigForFrogs.yml

thanks,

Martín.

**Minor formatting edits by @atruskie**

**Comment by atruskie** [comment]
Okay, so I've broken your command down into multiple lines to show what should be changed:

```diff
  D:\AP\AnalysisPrograms.exe DrawLongDurationSpectrograms
- "D:/AP/results_AP_laguna/Mixdown_laguna.wav/Towsey.Acoustic/Mixdown_laguna__Towsey.Acoustic.SUM.csv"
+ "D:/AP/results_AP_laguna/Mixdown_laguna.wav/Towsey.Acoustic"
+ "D:/AP/FC_spectrogram_laguna"
- SpectrogramFalseColourConfig.yml 
- "D:\AP\FC_spectrogram_laguna\Mixdown_laguna__Towsey.Acoustic.SUM.csv"
+ -fcs SpectrogramFalseColourConfig.yml 
- IndexPropertiesConfigForFrogs.yml
+ -i IndexPropertiesConfig.yml
```
Your script has an impedance: you've adapted a script used for analyzing **multiple** audio recordings, and tried to use it with result data for a **single** recording.  Thus the loop you have is not well suited to the task at hand. Either loop over multiple results, or convert the script to work on a single result set.

Assuming looping over multiple result set's is more interesting:
```diff
###AP_analysis###
rm(list=ls())
##Scripting with R
# Set the directory containing the files

- "D:/AP/results_AP_laguna/Mixdown_laguna.wav/Towsey.Acoustic" -> directory
+ "D:/AP/results_AP_laguna" -> directory

# The directory to store the results

 "D:/AP/FC_spectrogram_laguna"-> base_output_directory 

# Get a list of audio files inside the directory
# (Get-ChildItem is just like ls, or dir)

- files <- list.files(directory, pattern = ".csv", full.names = TRUE)
+ files <- list.dirs(directory, full.names = TRUE)

- files

# iterate through each file
for(file in files) {
  message("Processing ", file) 
  
  # get just the name of the file
  file_name <- basename(file)
  
  # make a folder for results
  output_directory <- normalizePath(file.path(base_output_directory, file_name))
  dir.create(output_directory, recursive = TRUE)
  
  # prepare command
-   command <- sprintf('DrawLongDurationSpectrograms "%s" SpectrogramFalseColourConfig.yml "%s" IndexPropertiesConfigForFrogs.yml', file, output_directory)
+   command <- sprintf('DrawLongDurationSpectrograms "%s" "%s" -fcs SpectrogramFalseColourConfig.yml -ip IndexPropertiesConfig.yml', file, output_directory)
 
  # finally, execute the command
  system2("D:/AP/AnalysisPrograms.exe", command)
}
```

It's also concerning you are storing the results within AP.exe's directory. This is **strongly discouraged**. If you upgrade AP.exe (or use the upgrader script): all files in AP.exe's directory will be deleted (permanently). 

And finally, for your RScript, consider not using the `rm(list=ls()` pattern. Read here https://www.tidyverse.org/articles/2017/12/workflow-vs-script/ for more info.

See how that goes 🙂

**Comment by tinchobulen** [comment]
Thanks @atruskie!

so, I tried again with the corrected sript, but still no success. 

My main question is: the FC spectrogram analysis works out over the several .csv files genetarated by the audio2csv command? or do I have to indicate only one .csv file per analysis? Thats why I previously typed: 

files <- list.files(directory, pattern = ".csv", full.names = TRUE)

Also, I tried out in the power shell environment. It seems the problem is that the program doesn't recognize the folder where the results are or I'm typing the wrong command or argument (in my case: Unrecognized command or argument 'D:\AP\results_AP_laguna\Mixdown_laguna.wav\Towsey.Acoustic').

please find bellow my new PowerShell command

D:\AP\AnalysisPrograms.exe DrawLongDurationSpectrograms D:\AP\results_AP_laguna\Mixdown_laguna.wav\Towsey.Acoustic D:\FC_spectrogram_laguna -ip D:\AP\ConfigFiles\IndexPropertiesConfig.yml -fcs D:\AP\ConfigFiles\SpectrogramFalseColourConfig.yml

please find attached the log file:

[log_20190724T122708Z.txt](https://github.com/QutEcoacoustics/audio-analysis/files/3426825/log_20190724T122708Z.txt)

my new R script: 

###AP_analysis###
##Scripting with R
# Set the directory containing the files

"D:/AP/results_AP_laguna" -> directory


# The directory to store the results

 "D:/FC_spectrogram_laguna"-> base_output_directory 

# Get a list of audio files inside the directory
# (Get-ChildItem is just like ls, or dir)

 files <- list.dirs(directory, full.names = TRUE)

files

# iterate through each file
for(file in files) {
  message("Processing ", file) 
  
  # get just the name of the file
  file_name <- basename(file)
  
  # make a folder for results
  output_directory <- normalizePath(file.path(base_output_directory, file_name))
  dir.create(output_directory, recursive = TRUE)
  
  # prepare command
  command <- sprintf(command <- sprintf('DrawLongDurationSpectrograms "%s" "%s" -fcs SpectrogramFalseColourConfig.yml -ip IndexPropertiesConfigForFrogs.yml', file, output_directory))
  
  # finally, execute the command
  system2("D:/AP/AnalysisPrograms.exe", command)
}

thanks again!

cheers,

M.

**Comment by atruskie** [comment]
> My main question is: the FC spectrogram analysis works out over the several .csv files genetarated by the audio2csv command? or do I have to indicate only one .csv file per analysis? Thats why I previously typed:

No. False colour spectrograms use multiple acoustic indices (and thus multiples of the CSV files). When you generate the image you need to point AP.exe to an _entire_ folder of indices results. In fact, if AP.exe doesn't find all the files it needs for a *whole* indices result set, it should error.

> Thats why I previously typed:
>
> files <- list.files(directory, pattern = ".csv", full.names = TRUE)

And that's why I provided you with a corrected statement:

```
 files <- list.dirs(directory, full.names = TRUE)
```
> Also, I tried out in the power shell environment. It seems the problem is that the program doesn't recognize the folder where the results are or I'm typing the wrong command or argument (in my case: Unrecognized command or argument 'D:\AP\results_AP_laguna\Mixdown_laguna.wav\Towsey.Acoustic').

Ah, so this one is my fault. It turns out neither of us read the help docs 😃.

If we run ` AnalysisPrograms.exe DrawLongdurationspectrograms --help` to see what the correct invocation is, we get:

```
QUT Ecoacoustics Analysis Programs - version 19.7.2.2 (DEBUG build, 2019-07-24T06:21:30.4747964Z)                                                                                                                                                                                                                Git branch-version: cross-platform-build-eb7e47b55445ab104a5d556993339864ea8eaea9, DirtyBuild:True, CI:000
Copyright 2019 QUT

[BETA] Produces long-duration, false-colour spectrograms from matrices of spectral indices.

Usage: AnalysisPrograms.exe DrawLongDurationSpectrograms [options]

Options:
  -i|--input-data-directory <INPUT_DATA_DIRECTORY>                          Directory where the input data is located.
  -o|--output-directory <OUTPUT_DIRECTORY>                                  Directory where the output is to go.
  -ip|--index-properties-config <INDEX_PROPERTIES_CONFIG>                   User specified file containing a list of indices and their properties.
  -fcs|--false-colour-spectrogram-config <FALSE_COLOUR_SPECTROGRAM_CONFIG>  Config file specifying directory containing indices.csv files and other parameters.
  -?|-h|--help                                                              Show help information
  -D|--debug                                                                Do not show the debug prompt AND automatically attach a debugger. Has no effect in RELEASE builds
  -n|--no-debug                                                             Do not show the debug prompt and do not attach a debugger. Has no effect in RELEASE builds
  -l|--log-level <LOG_LEVEL>                                                Set the log verbosity level. Valid values: None = 0, Error = 1, Warn = 2, Info = 3, Debug = 4, Trace = 5, Verbose = 6, All = 7
  -v                                                                        Set the logging to be verbose. Equivalent to LogLevel = Debug = 4
  -vv                                                                       Set the logging to very verbose. Equivalent to LogLevel = Trace = 5
  -vvv                                                                      Set the logging to very very verbose. Equivalent to LogLevel = ALL = 7
  --quiet                                                                   Reduce console logging to WARN and ERROR. Full logs still logged in file.
```

From that, we can see that `input-data-directory` and `output-directory` actually need a prefix before the argument (`-i` and `-o` respectively).

This version of your command should work:

```
D:\AP\AnalysisPrograms.exe DrawLongDurationSpectrograms -i D:\AP\results_AP_laguna\Mixdown_laguna.wav\Towsey.Acoustic -o D:\FC_spectrogram_laguna -ip D:\AP\ConfigFiles\IndexPropertiesConfig.yml -fcs D:\AP\ConfigFiles\SpectrogramFalseColourConfig.yml
```

And a modification to your RScript:

```diff
# prepare command
-   command <- sprintf(command <- sprintf('DrawLongDurationSpectrograms "%s" "%s" -fcs SpectrogramFalseColourConfig.yml -ip IndexPropertiesConfigForFrogs.yml', file, output_directory))
+   command <- sprintf(command <- sprintf('DrawLongDurationSpectrograms -i "%s" -o "%s" -fcs SpectrogramFalseColourConfig.yml -ip IndexPropertiesConfigForFrogs.yml', file, output_directory))

```

**Comment by tinchobulen** [comment]
Hello @atruskie 

sorry for my late response! had a lot of work these past weeks.

I ran the corrected R script. 
But it seems AP.exe doesn't finds the IndexPropertiesConfig.yml files. They are in a folder named ConfigFiles inside AP folder.
I will not give up! I will still try again to run the script.
Also ran the PowerShell command and the same response comes out (Error level 1)

Please find attached the logs files. 

[log_20190803T205501Z.txt](https://github.com/QutEcoacoustics/audio-analysis/files/3482969/log_20190803T205501Z.txt)
[log_20190803T205843Z.txt](https://github.com/QutEcoacoustics/audio-analysis/files/3482970/log_20190803T205843Z.txt)

cheers,

MB.

**Comment by atruskie** [comment]
Okay, in the first log, you corrected for the error by providing the full path to the config files - that fixed that particular problem, well done 👍

The second log, that error is particularly bad (my apologies) but happens because there is no `IndexGenerationData.json` file found in the `D:\AP\results_AP_laguna\Mixdown_laguna.wav\Towsey.Acoustic` folder. Does that folder have that file/
