### ISSUE TITLE
Remove R3D as spectral index

### ISSUE THREAD

**Issue by towsey** [QutEcoacoustics/audio-analysis#276]
Removing R3D as spectral index because it does not add anything useful to the spectral indices that we already have. It did not work as I originally expected it to.

**Comment by towsey** [comment]
The last edits have corrected all failed unit tests.

**Comment by atruskie** [comment]
@towsey, yup I saw 👍, just waiting for the last CI build to finish

**Comment by atruskie** [comment]
Closed in #277

**Comment by atruskie** [comment]
Further context from @towsey:

> The reason I removed R3D spectral is simply that it was not doing what I originally intended. It was calculated by averaging RHZ, RPS and RNG, that is, the horizontal, positive and negative slope ridges. It turned out to be highly influenced by and highly correlated with RVT (vertical ridges). If you wish to resurrect R3D, you can simply write an R script and average the RHZ, RPS and RNG matrices which are still calculated. Alternatively you could try to use one of those in place of the original R3D. I hope this helps.
