### ISSUE TITLE
Generic Component Recognition

### ISSUE THREAD

**Issue by towsey** [QutEcoacoustics/audio-analysis#281]
This issue concerns setting up a system within AnalysisPrograms which allows users to write their own call recognition system by editing config files only. The idea is to have a set of classes which recognize generic acoustic syllables that are common in the calls of vocalizing animals. The current intention is to write three such generic recognizers: for oscillations, whistles and "blobs".   

The user will  only have to edit a config file and will not have to write C# code.

**Comment by atruskie** [comment]
Proposed algorithms:

- [ ] Oscillation detector
- [ ] Whistle detector
- [ ] Blob detector
- [ ] AED detector

Design details:

- Algorithms are not chainable (i.e. input is always audio and output is always an audio event)
- Algorithms *could* run concurrently
- Events from each algorithm are concatenated into one output event file
- Each _profile_ runs one algorithm

Work items:

- [ ] static classes for config deserialization
- [ ] write a loop to process each algorithm
- [ ] ignore the config file for the moment
- [ ] DO NOT copy another recognizer (as per 2bfa889). There is so much unrelated code and commentary in current recognizers that are not needed.
