### ISSUE TITLE
Calculate a new Summary Index - spectral centroid

### ISSUE THREAD

**Issue by towsey** [QutEcoacoustics/audio-analysis#292]
A recent paper from Sussex University (Alice Eldridge and colleagues) finds that the Spectral Centroid (SC) is a good summary index correlated with degree of "naturalness" of a bush soundscape.

The SC is a standard index which indicates where the centre of spectral energy is located.

PROPOSAL
Since this is an easy index to calculate the proposal is that we sould add this to the list of summary indices that we calculate.

**Comment by atruskie** [comment]
Sounds great. After .Net Core merge.
