### ISSUE TITLE
System.InvalidOperationException: No process is associated with this object

### ISSUE THREAD

**Issue by agmacpha** [QutEcoacoustics/audio-analysis#299]
## Describe the bug
System.InvalidOperationException: No process is associated with this object

## Expected behavior 
Creating of LDFC using Towsey.Acoustic configuration file

### Instructions

- [x] I have followed the [instructions for reporting a bug](https://github.com/QutEcoacoustics/audio-analysis/blob/master/docs/bug_report.md) Yes :)

### I have attached a log:

[log_20200229T161853Z.txt](https://github.com/QutEcoacoustics/audio-analysis/files/4270571/log_20200229T161853Z.txt)
[log_20200229T161925Z.txt](https://github.com/QutEcoacoustics/audio-analysis/files/4270572/log_20200229T161925Z.txt)

### The command I used:

```

mono AnalysisPrograms.exe audio2csv BG-0003-010_20150614_050000+1100.flac Towsey.Acoustic ./

```

### The config file I used:

[log_20200229T161853Z.txt](https://github.com/QutEcoacoustics/audio-analysis/files/4270573/log_20200229T161853Z.txt)

## Screenshots

![bugscreenshot](https://user-images.githubusercontent.com/36797853/75611201-a7ebbe00-5ad5-11ea-9214-db205a499665.png)

**Comment by atruskie** [comment]
Thanks for the report. 

Can you please submit a verbose log? It'll contain much more information.  Append `--log-level 7` to one of you failing commands and attach the log in a new message.

Cheers!

**Comment by agmacpha** [comment]
![towseyacoustic](https://user-images.githubusercontent.com/36797853/75684450-0e97e580-5c56-11ea-8b9e-d3b27f71dc64.png)

[log_20200302T141701Z.txt](https://github.com/QutEcoacoustics/audio-analysis/files/4275823/log_20200302T141701Z.txt)

Attaching verbose log and screenshot - much appreciated!

**Comment by atruskie** [comment]
Okay, there's nothing obvious in the log. It looks like the first time we try and get information about the target file, the process exits immediately without retrieving anything from stdout or stderr.

Can you please send me the test data? You can email me a link privately and we can agree to whatever privacy and copyright terms you need us to.

Meanwhile, can you please run the following command and return the output for me:

```
ls -laR /Users/alexandremacphail/AP/audio-utils
```

**Comment by atruskie** [comment]
(data was sent privately)

I've run this on my computer. Problem not reproduced with Windows 10 and Ubuntu 18 (Mono version 6.8) (`mono /AP/AnalysisPrograms.exe audio2csv ./Downloads/BG-0003-010_20150101_050000+1100.flac Towsey.Acoustic.yml /mnt/c/Temp/test3`).

I can't reproduce. So we're looking at some kind of Mac/culture/device-specific bug. 

@peichins can I get you to try and replicate this on your machine?

**Comment by agmacpha** [comment]
Thanks for the help and attention @atruskie @peichins !

**Comment by atruskie** [comment]
I thought I had reproduced this, but it turns I hadn't.

Does the issue occur for you in with an older version? Can you try with one of the older versions from last year?

ping @peichins.
