### ISSUE TITLE
Default value for frame overlap

### ISSUE THREAD

**Issue by towsey** [QutEcoacoustics/audio-analysis#307]
The default value for frame/window overlap is currently set at 0.5. (See class SonogramConfig, line 24.)
This should be set = zero (0.0).
The frame step can be set directly or indirectly through windowOverlap. Both means are useful at different times. However currently setting one does not always set the other. In particular, setting the frame step in Generic Profiles does not reset the windowOverlap.
Changing the default windowOVerlap to zero may cause some tests to fail.

**Comment by atruskie** [comment]
I don't think this will have much effect.

We generally set window overlap to 0 almost everywhere. I doubt that default is ever actually used.

Change the default, run the tests, see if there are any failures, and we can see what the right thing to do after that it is.

As for the overlap/frameStep duality: a couple of unit tests for the `SonogramConfig` class should be enough they are always set consistently.

**Comment by towsey** [comment]
The default is used which is how I picked up the problem.

**Comment by atruskie** [comment]
Where?

**Comment by towsey** [comment]
Line 142 in the same class.

**Comment by atruskie** [comment]
As in:

https://github.com/QutEcoacoustics/audio-analysis/blob/63e6299be51bf1cf7215e6adbf02bb0c55f25b1b/src/AudioAnalysisTools/StandardSpectrograms/BaseSonogramConfig.cs#L141

Then yes, the default is set. But we override it almost everywhere. Have you found a case where that default is not used in real world code?

**Comment by atruskie** [comment]
Discussed offline. It looks like the root cause of this was introduced in 

https://github.com/QutEcoacoustics/audio-analysis/blame/2b9fa60caf62955083a75731be644bc8088f9485/src/AnalysisPrograms/Recognizers/GenericRecognizer.cs#L295
