### ISSUE TITLE
Expose ImageChrome option in SpectrogramFalseColourConfig

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/audio-analysis#352]
## Is your feature request related to a problem? Please describe.

Sometimes I'd like to produce a FCS without any of the axes, legends, or gridlines.

## Describe the solution you'd like

Expose the internal `ImageChrome` option of the FCS rendering methods by adding a config file property in `SpectrogramFalseColourConfig`.

## Describe alternatives you've considered

N/A

## Additional context

This issue was filed on behalf of an external collaborator.

**Comment by mtchl** [comment]
Hey I would really like this functionality too. I'm hoping to include some FCS in a web application so plain images would be ideal
