### ISSUE TITLE
Bug at line259 in EventFilters.cs

### ISSUE THREAD

**Issue by towsey** [QutEcoacoustics/audio-analysis#466]
## Describe the bug
There is an attempt to write the contents of a List<double> when there may be no elements in the list.

## Expected behavior 
Should only write the list if it contains at least one double.

## Diagnostics
Lines 259 and 260 should be moved and inserted at current line 279 by which stage it has been established that the list contains values.

**Comment by atruskie** [comment]
Pro tip: use the copy permalink option to insert a code snippet:

![image](https://user-images.githubusercontent.com/1452968/112972896-1a751480-9194-11eb-85c1-11ea2093a437.png)

What ill effect does this bug have?

In general, I'm against altering behaviour for special cases. If a list is empty than the debug line should print an empty list (or an `"<empty>"` sentinel value).

**Comment by towsey** [comment]
I shifted the two lines of code to where they should be, since there is no point writing something irrelevant to log.

**Comment by atruskie** [comment]
Closed by #475
