### ISSUE TITLE
Plot graphs do not rescale when combined with plots from other spectrogram scales

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/audio-analysis#469]
## Actual behaviour:

In a generic recogniser one can use different spectrogram settings for each profile. If the window sizes are different then the diagnostic plots produced are rendered with different amounts of data and produce a not so useful image.

## How to reproduce this bug:

1. Create a generic recogniser with two profiles
2. Ensure each profile uses a different spectrogram frame size
3. View the output debug spectrogram

## Additional Details

![K-P-THINNING_20130209_062400_0-0 5min__Image_not_cheating](https://user-images.githubusercontent.com/1452968/113242527-8a9aac00-92f4-11eb-98aa-9a2cc85c8dc1.png)

You can see one of the plots is much longer than the rest of the content in the image.

**Comment by towsey** [comment]
All the unit tests appear to be passing. In Plot unit test, rescaling of plots is successful.
